### PR TITLE
fix: remove lockfiles to avoid symlinks in VC

### PR DESCRIPTION
**Pull request by NWRichmond**
**Story:** [LS-1393](https://nacelle.atlassian.net/browse/LS-1393)

### Type of Change

- [x] Bug fix

### What is being changed and why?

In #66, `package-lock.json` files were added to source control. This created problems, because symlinks created by `lerna bootstrap` led to problems during deployment and when scaffolding a new project from `examples/*`.

This PR keeps `packages/` and `examples/`' lock files out of version control. The root-level `package-lock.json` is still tracked, as described here: https://www.linkedin.com/pulse/things-i-wish-had-known-when-started-javascript-monorepo-gore.

### How to Test

Deploy previews for `examples/nextjs` should deploy without issues.

_Update: 👍 (https://nacelle-nextjs-example-git-ls-1393-remove-lockfiles-nacelle.vercel.app)_

To test locally:
```
npx degit https://github.com/getnacelle/nacelle-react/examples/nextjs\#LS-1393-remove-lockfiles nextjs-demo
cd nextjs-demo
npm i
```
Next, add a `.env` based on the variables outlined in `.env.example` (I can DM you one in Slack).

Finally, `npm run dev`, and navigate to [`localhost:4000`](http://localhost:4000), where the Next.js site should be available .

### CODE REVIEW

**Comment by NWRichmond** [comment]
Note: the `nacelle-gatsby-example` deploy is failing, for unrelated reasons - there seems to have been a change in Vercel's Node environments' npm. What's a npm `warning` locally appears to be a npm `error` on Vercel. We can come back and address that later.

**Review by mdarrik — APPROVED** [review]
lgtm! Does feel a bit weird/hacky though.

**Comment by NWRichmond** [comment]
@mdarrik thanks for the review! And yes, I agree - it's a `lerna` thing that isn't well documented.

**Review by jasonredick — APPROVED** [review]
Works for me 👍

**Comment by NWRichmond** [comment]
Thank you both for the reviews!

**Pull request merged**
